services:
  web:
    container_name: my_app
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: "project"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "892255"
    ports:
      - '5432:5432'
