"""second

Revision ID: 23981dec89ad
Revises: 1608dbe5d685
Create Date: 2025-01-30 14:26:26.138621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23981dec89ad'
down_revision: Union[str, None] = '1608dbe5d685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('author_login', sa.String(), nullable=False),
    sa.Column('author_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_author_author_id'), 'author', ['author_id'], unique=False)
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_category_category_id'), 'category', ['category_id'], unique=False)
    op.create_table('article',
    sa.Column('pk_article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('fk_author_id', sa.Integer(), nullable=False),
    sa.Column('fk_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_author_id'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['fk_category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('pk_article_id')
    )
    op.create_index(op.f('ix_article_pk_article_id'), 'article', ['pk_article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_pk_article_id'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_category_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_author_author_id'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
