"""1

Revision ID: 45a2b2afe83c
Revises: cf44f6f4bbe7
Create Date: 2025-02-04 15:39:24.946156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a2b2afe83c'
down_revision: Union[str, None] = 'cf44f6f4bbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('pk_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk_role_id')
    )
    op.create_index(op.f('ix_user_role_pk_role_id'), 'user_role', ['pk_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_pk_role_id'), table_name='user_role')
    op.drop_table('user_role')
    # ### end Alembic commands ###
