"""add_role_to_user

Revision ID: 6a95385d29ad
Revises: 45a2b2afe83c
Create Date: 2025-02-04 15:58:27.749290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a95385d29ad'
down_revision: Union[str, None] = '45a2b2afe83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('fk_role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'author', 'user_role', ['fk_role'], ['pk_role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'fk_role')
    # ### end Alembic commands ###
