"""add email

Revision ID: b7ab7e43fb07
Revises: 275033913bcf
Create Date: 2025-01-30 14:34:58.154948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ab7e43fb07'
down_revision: Union[str, None] = '275033913bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('author_email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'author_email')
    # ### end Alembic commands ###
