"""'delete_cascade'

Revision ID: cf44f6f4bbe7
Revises: b7ab7e43fb07
Create Date: 2025-02-03 15:28:14.483757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf44f6f4bbe7'
down_revision: Union[str, None] = 'b7ab7e43fb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
